"""Doing some testing"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_test.ipynb.

# %% auto 0
__all__ = ['foo', 'test_func_2']

# %% ../nbs/00_test.ipynb 3
def foo(): pass

# %% ../nbs/00_test.ipynb 6
def test_func_2(n):
    return n*n*n
